// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"edtech-app/internal/course/delivery/http"
	course2 "edtech-app/internal/course/repository"
	course3 "edtech-app/internal/course/usecase"
	"edtech-app/internal/lesson/repository"
	lesson2 "edtech-app/internal/lesson/usecase"
	"edtech-app/internal/product/repository"
	product2 "edtech-app/internal/product/usecase"
	"edtech-app/pkg/fileupload/cloudinary"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitiliazedService(db *gorm.DB) *course.CourseHandler {
	courseRepository := course2.NewCourseRepository(db)
	fileUpload := fileupload.NewFileUpload()
	productRepository := product.NewProductRepository(db)
	productUseCase := product2.NewProductUseCase(productRepository, fileUpload)
	lessonRepository := lesson.NewLessonRepository(db)
	lessonUseCase := lesson2.NewLessonUseCase(lessonRepository, fileUpload)
	courseUseCase := course3.NewCourseUseCase(courseRepository, fileUpload, productUseCase, lessonUseCase)
	courseHandler := course.NewCourseHandler(courseUseCase)
	return courseHandler
}
