// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"gorm.io/gorm"
	"edtech-app/internal/product/delivery/http"
	product2 "edtech-app/internal/product/repository"
	product3 "edtech-app/internal/product/usecase"
	"edtech-app/pkg/fileupload/cloudinary"
)

// Injectors from wire.go:

func InitiliazedService(db *gorm.DB) *product.ProductHandler {
	productRepository := product2.NewProductRepository(db)
	fileUpload := fileupload.NewFileUpload()
	productUseCase := product3.NewProductUseCase(productRepository, fileUpload)
	productHandler := product.NewProductHandler(productUseCase)
	return productHandler
}
